spring.application.name=PPD
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=storage
spring.data.mongodb.username=app
spring.data.mongodb.password=pass

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
